sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- "./install/install_and_test.sh"
script:
- mv install/package.xml force-app/main/default
- "./install/deploy.sh"
